name: bloc_helpers
description: Set of helpers class and function to implements Bloc pattern
homepage: https://github.com/lejard-h/bloc_helpers
author: Hadrien Lejard <hadrien.lejard@gmail.com>
version: 0.3.1

environment:
  sdk: '>=1.23.0 <3.0.0'

dependencies:
  rxdart: ^0.21.0
  meta: ^1.1.0
  test: ^1.5.0